In [16]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
data = pd.read_csv('heart.csv')
data.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

2. Обучите на этих данных простую модель логистической регрессии и выведите метрику точности (accuracy).

In [17]:
from sklearn.linear_model import LinearRegression
X = data.drop('output', axis=1)
y = data['output']
lr_model = LinearRegression()
lr_model.fit(X, y)

LinearRegression()

In [18]:
lr_model.score(X, y)

0.5175499644256842

3. Разделите датасет на две части - первую половину используйте для обучения, а вторую - для оценки точности. Сравните значения метрик.

In [19]:
x_train, y_train = X[:200], y[:200]
x_train.shape, y_train.shape

((200, 13), (200,))

In [20]:
x_test, y_test = X[200:], y[200:]
x_test.shape, y_test.shape

((103, 13), (103,))

In [21]:
lr_model.fit(x_train, y_train)

LinearRegression()

In [22]:
lr_model.score(x_train, y_train)

0.45405804018236184

In [23]:
lr_model.predict(x_test)

array([ 0.75194431,  0.1589634 ,  0.45760619,  0.6185906 , -0.20536379,
        0.63463611,  0.34723006,  0.31155265,  0.4546555 ,  0.6752418 ,
        0.73309023,  0.14842541,  0.56768794,  0.55630577,  0.44877022,
        0.26813972,  0.73318975,  0.10733601,  0.21077554,  0.44121948,
        0.01226233, -0.07190108,  0.8527078 ,  0.00574668,  0.21386137,
        0.33361744,  0.41562629,  0.44133546,  0.95184152,  0.61487406,
        1.0651674 ,  0.23974811,  0.39561276,  0.22404809,  0.14463121,
        0.53857414,  0.54039987,  0.37441532,  0.49652804,  0.59427433,
        0.40497086,  0.88486639,  0.45384374,  0.33911121,  0.40688837,
        0.6005157 ,  0.25104764,  0.70110343,  0.79235655,  0.38460263,
       -0.13155312,  0.21930841,  0.39190055,  0.35642161,  1.05394538,
        0.3062811 ,  0.03386762,  0.45263146,  0.73724523,  0.57409542,
        0.55453266,  0.8048266 ,  0.15974414,  0.53138964,  0.53636692,
        0.61174202,  0.49997098,  0.63558869,  0.0727705 ,  0.26428147,
        0.56682765,  0.68170541,  0.59395474,  0.6838095 ,  0.40626029,
        0.52989096,  0.36097258,  0.8156664 ,  0.81227857,  0.17846966,
        0.5854293 ,  0.87827927,  0.78798229,  0.82580133,  0.31739102,
        0.21601046,  0.9641996 ,  0.8475039 ,  0.18941333,  0.5263364 ,
        0.73561087,  0.18991621,  0.42098122,  0.79235083,  0.51581958,
        0.0113101 ,  0.87671559,  0.50776324,  0.71249151,  0.84682237,
        0.19458025,  0.4292016 ,  0.92737323])

In [24]:
lr_model.score(x_test, y_test)

0.0

4. Разделите датасет на две части случайным образом. Повторите анализ.

In [26]:
N = int(X.shape[0] * 0.8)

x_train, y_train, x_test, y_test = X[:N], y[:N], X[N:], y[N:]
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [27]:
lr_model_fn = LinearRegression()
lr_model_fn.fit(x_train, y_train)

LinearRegression()

In [28]:
lr_model_fn.score(x_train, y_train)

0.5452486098240781

In [29]:
lr_model_fn.score(x_test, y_test)

0.0

5. Разделите датасет с помощью библиотечной функции. Повторите анализ несколько раз.

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
lr_model_fn.fit(X_train, y_train)

LinearRegression()

In [31]:
lr_model_fn.predict(X_test)

array([ 0.70835624,  0.23906604,  0.66120829,  0.09630921,  0.66658859,
        0.73983727,  0.94711377, -0.19975058,  0.69734504,  1.04130121,
        0.70806842,  0.43611143, -0.30176255,  1.09831568,  0.22916601,
        0.54905673,  0.66200671,  0.48900934, -0.17225206,  0.63903547,
        0.67195332,  0.04159132,  0.18491459, -0.35354893,  0.88607199,
        0.0996207 ,  0.45865101,  0.33482633,  0.31299001,  0.44446979,
        0.98054725,  0.16432957,  0.3283534 ,  0.5676787 ,  0.03158271,
       -0.10246647,  0.71213129,  0.67579197,  0.63042444,  0.77696067,
        0.2464155 ,  0.67801285,  0.09811027,  0.50297533,  1.04502157,
       -0.01857288, -0.1893683 ,  0.8939162 ,  0.22063997,  0.91476711,
        0.99570854,  0.38333848,  1.23242723, -0.17545243,  0.58803613,
        0.67935897,  0.89845614,  0.64288185,  0.40491079,  0.1942325 ,
        0.58521023])

In [32]:
lr_model_fn.score(X_train, y_train)

0.542182155395534

In [33]:
lr_model_fn.score(X_test, y_test)

0.3565156333892123

6. Постройте матрицу классификации и отчет о классификации для обученной модели для обучающей и тестовой выборок. Проинтерпретируйте полученные значения.

In [34]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
y_test_pred = lr_model.predict(x_test)
y_train_pred = lr_model.predict(x_train)
y_train_pred_binary = (y_train_pred >= 0.5).astype(int)
confusion_matrix(y_train, y_train_pred_binary)

array([[ 19,  85],
       [ 34, 104]])

In [35]:
y_test_pred_binary = (y_test_pred >= 0.5).astype(int)
confusion_matrix(y_test, y_test_pred_binary)

array([[11, 23],
       [16, 11]])

In [36]:
print(classification_report(y_test, y_test_pred_binary))

              precision    recall  f1-score   support

           0       0.41      0.32      0.36        34
           1       0.32      0.41      0.36        27

    accuracy                           0.36        61
   macro avg       0.37      0.37      0.36        61
weighted avg       0.37      0.36      0.36        61

7. Подсчитайте для построенной модели значение всех метрик эффективности классификации на тестовой и обучающей выборках. Нужно использовать следующие метрики: accuracy, precision, recall, f1.

In [37]:
metrics = pd.DataFrame({
    "Train": [
        accuracy_score(y_train, y_train_pred_binary),
        precision_score(y_train, y_train_pred_binary),
        recall_score(y_train, y_train_pred_binary),
        f1_score(y_train, y_train_pred_binary),
    ],
    "Test": [
        accuracy_score(y_test, y_test_pred_binary),
        precision_score(y_test, y_test_pred_binary),
        recall_score(y_test, y_test_pred_binary),
        f1_score(y_test, y_test_pred_binary),
    ],
}, index = ["Accuracy", "Precision", "Recall", "F1"])

metrics

              Train      Test
Accuracy   0.508264  0.360656
Precision  0.550265  0.323529
Recall     0.753623  0.407407
F1         0.636086  0.360656

## Задания для самостоятельного выполнения

1. Повторите анализ для других видов моделей. Используйте 5-10 разных классов моделей. Подсчитывайте только метрики на тестовой выборке.

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, BaggingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score
from sklearn.model_selection import cross_val_score

In [44]:
def train_and_evaluate_models_classification(X_train, X_test, y_train, y_test):
    models = {
        "Логистическая регрессия": LogisticRegression(max_iter=1000),
        "Метод опорных векторов (линейное ядро)": SVC(kernel='linear', probability=True),
        "Метод опорных векторов (гауссовое ядро)": SVC(kernel='rbf', probability=True),
        "Метод ближайших соседей": KNeighborsClassifier(),
        "Дерево решений": DecisionTreeClassifier(),
        "Случайный лес": RandomForestClassifier(),
        "Градиентный бустинг": GradientBoostingClassifier(),
        "Беггинг": BaggingClassifier(),
        "Многослойный перцептрон": MLPClassifier(max_iter=1000)
    }

    for model_name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_pred_proba = model.predict_proba(X_test) # Берём вероятность положительного класса
        
        roc_auc = roc_auc_score(y_test, y_pred_proba, multi_class="ovr")
        accuracy = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="weighted")

        cv_score = cross_val_score(model, X_train, y_train, cv=5, scoring='f1_weighted').mean()

        print(f"{model_name}:")
        print(f"  ROC-AUC: {roc_auc:.4f}")
        print(f"  Accuracy: {accuracy:.4f}")
        print(f"  F1-score: {f1:.4f}")
        print(f"  Кросс-валидация (F1-score): {cv_score:.4f}\n")
from sklearn.datasets import load_iris
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)
classification_results = train_and_evaluate_models_classification(X_train, X_test, y_train, y_test)
print("Classification Results:")
print(classification_results)

Логистическая регрессия:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9657

Метод опорных векторов (линейное ядро):
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9574

Метод опорных векторов (гауссовое ядро):
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9477

Метод ближайших соседей:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9393

Дерево решений:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9410

Случайный лес:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9410

Градиентный бустинг:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9410

Беггинг:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9415

Многослойный перцептрон:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9657

Classification Results:
None

2. Повторите анализ для другого датасета по вашему выбору. Используйте несколько моделей для сравнения. Используйте датасет для множественной классификации.

In [49]:
from sklearn.datasets import load_wine
import warnings
warnings.filterwarnings('ignore')
wine = load_wine()
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.2, random_state=42)
classification_results_wine = train_and_evaluate_models_classification(X_train, X_test, y_train, y_test)
print("\nMulti-class Classification Results (Wine Dataset):")
print(classification_results_wine)

Логистическая регрессия:
  ROC-AUC: 1.0000
  Accuracy: 0.9722
  F1-score: 0.9722
  Кросс-валидация (F1-score): 0.9502

Метод опорных векторов (линейное ядро):
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9426

Метод опорных векторов (гауссовое ядро):
  ROC-AUC: 0.9094
  Accuracy: 0.8056
  F1-score: 0.8024
  Кросс-валидация (F1-score): 0.6027

Метод ближайших соседей:
  ROC-AUC: 0.8828
  Accuracy: 0.7222
  F1-score: 0.7222
  Кросс-валидация (F1-score): 0.6539

Дерево решений:
  ROC-AUC: 0.9521
  Accuracy: 0.9444
  F1-score: 0.9449
  Кросс-валидация (F1-score): 0.9218

Случайный лес:
  ROC-AUC: 1.0000
  Accuracy: 1.0000
  F1-score: 1.0000
  Кросс-валидация (F1-score): 0.9713

Градиентный бустинг:
  ROC-AUC: 0.9903
  Accuracy: 0.9444
  F1-score: 0.9440
  Кросс-валидация (F1-score): 0.9221

Беггинг:
  ROC-AUC: 0.9978
  Accuracy: 0.9722
  F1-score: 0.9718
  Кросс-валидация (F1-score): 0.9500

Многослойный перцептрон:
  ROC-AUC: 0.8515
  Accuracy: 0.4167
  F1-score: 0.2829
  Кросс-валидация (F1-score): 0.5537


Multi-class Classification Results (Wine Dataset):
None

3. Повторите анализ для датасета, предназначенного для решения задачи регрессии. Используйте все метрики качества регрессии, изученные на лекции. Постройте 5 - 10 разных моделей регрессии.

In [51]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import cross_val_score
def train_and_evaluate_models(X_train, X_test, y_train, y_test):
    models = {
        "Линейная регрессия": LinearRegression(),
        "Гребневая регрессия": Ridge(),
        "Лассо регрессия": Lasso(),
        "ElasticNet регрессия": ElasticNet(),
        "Метод опорных векторов (без ядра)": SVR(kernel='linear'),
        "Метод опорных векторов (гауссовое ядро)": SVR(kernel='rbf'),
        "Метод опорных векторов (полиномиальное ядро)": SVR(kernel='poly'),
        "Метод ближайших соседей": KNeighborsRegressor(),
        "Многослойный перцептрон": MLPRegressor(max_iter=1000),
        "Дерево решений": DecisionTreeRegressor(),
        "Случайный лес": RandomForestRegressor(),
        "Беггинг": BaggingRegressor()
    }

    for model_name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        
        # Метрики
        r2 = r2_score(y_test, y_pred)
        mae = mean_absolute_error(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred)
        rmse = np.sqrt(mse)
        
        # Кросс-валидация - промежуточный этап оценки модели
        cv_score = cross_val_score(model, X_train, y_train, cv=5, scoring='r2').mean()

        # Выводим результаты
        print(f"{model_name}:")
        print(f"  R²: {r2:.4f}")
        print(f"  MAE: {mae:.4f}")
        print(f"  MSE: {mse:.4f}")
        print(f"  RMSE: {rmse:.4f}")
        print(f"  Кросс-валидация: {cv_score:.4f}\n")
diabetes = load_diabetes()
X, y = diabetes.data, diabetes.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
train_and_evaluate_models(X_train, X_test, y_train, y_test)

Линейная регрессия:
  R²: 0.4526
  MAE: 42.7941
  MSE: 2900.1936
  RMSE: 53.8534
  Кросс-валидация: 0.4493

Гребневая регрессия:
  R²: 0.4192
  MAE: 46.1389
  MSE: 3077.4159
  RMSE: 55.4745
  Кросс-валидация: 0.3802

Лассо регрессия:
  R²: 0.3576
  MAE: 49.7303
  MSE: 3403.5757
  RMSE: 58.3402
  Кросс-валидация: 0.3238

ElasticNet регрессия:
  R²: -0.0025
  MAE: 63.7059
  MSE: 5311.2128
  RMSE: 72.8781
  Кросс-валидация: -0.0216

Метод опорных векторов (без ядра):
  R²: 0.0203
  MAE: 61.9045
  MSE: 5190.3877
  RMSE: 72.0443
  Кросс-валидация: -0.0263

Метод опорных векторов (гауссовое ядро):
  R²: 0.1821
  MAE: 56.0237
  MSE: 4333.2860
  RMSE: 65.8277
  Кросс-валидация: 0.1122

Метод опорных векторов (полиномиальное ядро):
  R²: 0.2822
  MAE: 51.6617
  MSE: 3803.0441
  RMSE: 61.6688
  Кросс-валидация: 0.1794

Метод ближайших соседей:
  R²: 0.4302
  MAE: 42.7708
  MSE: 3019.0755
  RMSE: 54.9461
  Кросс-валидация: 0.3172

Многослойный перцептрон:
  R²: 0.3912
  MAE: 47.5220
  MSE: 3225.3020
  RMSE: 56.7917
  Кросс-валидация: 0.3764

Дерево решений:
  R²: 0.1017
  MAE: 53.4831
  MSE: 4759.3258
  RMSE: 68.9879
  Кросс-валидация: -0.1133

Случайный лес:
  R²: 0.4211
  MAE: 44.8203
  MSE: 3067.1645
  RMSE: 55.3820
  Кросс-валидация: 0.4042

Беггинг:
  R²: 0.3524
  MAE: 46.4449
  MSE: 3431.0274
  RMSE: 58.5750
  Кросс-валидация: 0.3487